<?php

namespace Tests\Unit;

use App\Services\VenueService;

use Illuminate\Support\Facades\Http;
use PHPUnit\Framework\TestCase;

class Venue4sqServiceTest extends TestCase
{
    public function setUp(): void
    {
        Http::fake();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_get_categories()
    {
        /*
        $venue4sqService = app()->make(VenueService::class);

        $venue4sqService->getCategories();*/

        Http::assertSent(function ($request) {
            return $request->hasHeader('X-First', 'foo') &&
                $request->url() == 'http://test.com/users' &&
                $request['name'] == 'Taylor' &&
                $request['role'] == 'Developer';
        });
    }

    public function test_get_place_groups()
    {

    }
}
